//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaiTapLonWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class chitietHDN
    {
        public string MaHDN { get; set; }
        public string MaSP { get; set; }
        public Nullable<int> SoLuongNhap { get; set; }
        public Nullable<int> DonGia { get; set; }
        public Nullable<int> ThanhTien { get; set; }
    
        public virtual hoadonnhap hoadonnhap { get; set; }
        public virtual sanpham sanpham { get; set; }
    }
}
