//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaiTapLonWeb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class webbangiayEntities4 : DbContext
    {
        public webbangiayEntities4()
            : base("name=webbangiayEntities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<chitietHDB> chitietHDBs { get; set; }
        public virtual DbSet<chitietHDN> chitietHDNs { get; set; }
        public virtual DbSet<dathang> dathangs { get; set; }
        public virtual DbSet<hinhanh> hinhanhs { get; set; }
        public virtual DbSet<hoadonban> hoadonbans { get; set; }
        public virtual DbSet<hoadonnhap> hoadonnhaps { get; set; }
        public virtual DbSet<khachhang> khachhangs { get; set; }
        public virtual DbSet<nhasx> nhasxes { get; set; }
        public virtual DbSet<quantri> quantris { get; set; }
        public virtual DbSet<sanpham> sanphams { get; set; }
        public virtual DbSet<soluong> soluongs { get; set; }
    }
}
