//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaiTapLonWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class soluong
    {
        public string MaSP { get; set; }
        public Nullable<int> size39 { get; set; }
        public Nullable<int> size40 { get; set; }
        public Nullable<int> size41 { get; set; }
        public Nullable<int> size42 { get; set; }
        public Nullable<int> size43 { get; set; }
    
        public virtual sanpham sanpham { get; set; }
    }
}
